# Generated by Django 4.0 on 2022-01-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_remove_books_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='image',
        ),
    ]
